# This is an example with only required properties:
version: 1
update_configs:
  - package_manager: "python"
    directory: "/"
    update_schedule: "live"
    allowed_updates:
      - match:
          update_type: "security"
